# Generated by Django 2.2.1 on 2019-07-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
